class quotable:
    quotations = \
        [
            'There\'s only one thing I hate more than lying: skim milk. Which is water that is lying about being milk.',
            'Dear frozen yogurt, you are the celery of desserts. Be ice cream or be nothing. Zero stars.',
            'There are three acceptable haircuts: high and tight, crew cut, buzz cut.',
            'The key to burning an ex-wife effigy is to dip it in paraffin wax and then toss the flaming bottle of isopropyl alcohol from a safe distance. Do not stand too close when you light an ex-wife effigy.',
            'Under my tutelage, you will grow from boys to men. From men into gladiators. And from gladiators into Swansons.',
            'On my deathbed, my final wish is to have my ex-wives rush to my side so I can use my dying breath to tell them both to go to hell one last time.',
            'Normally, if given the choice between doing something and nothing, I\'d choose to do nothing. But I will do something if it helps someone else do nothing. I\'d work all night, if it meant nothing got done.',
            'It\'s always a good idea to demonstrate to your coworkers that you are capable of withstanding a tremendous amount of pain.',
            'It\'s pointless for a human to paint scenes of nature when they can go outside and stand in it.',
            'I call this turf \'n\' turf. It\'s a 16-ounce T-bone and a 24-ounce porterhouse. Also, whiskey and a cigar. I am going to consume all of this at the same time because I am a free American.',
            'I\'m a simple man. I like pretty, dark-haired women, and breakfast food.',
            'There has never been a sadness that can\'t been cured by breakfast food.',
            'One rage every three months is permitted. Try not to hurt anyone who doesn\'t deserve it.',
            'I once worked with a guy for three years and never learned his name. Best friend I ever had. We still never talk sometimes.',
            'When people get too chummy with me I like to call them by the wrong name to let them know I don\'t really care about them.',
            'If any of you need anything at all, too bad. Deal with your problems yourselves, like adults.',
            'The government is a greedy piglet that suckles on a taxpayer\'s teat until they have sore, chapped nipples.',
            'I don\'t want to paint with a broad brush here, but every single contractor in the world is a miserable, incompetent thief.',
            'History began on July 4, 1776. Everything that happened before that was a mistake.',
            'Fishing relaxes me. It\'s like yoga, except I still get to kill something.',
            'America: The only country that matters. If you want to experience other \'cultures,\' use an atlas or a ham radio.',
            'Give a man a fish and feed him for a day. Don\'t teach a man to fish... and feed yourself. He\'s a grown man. And fishing\'s not that hard.',
            'Sting like a bee. Do not float like a butterfly. That\'s ridiculous.',
            'Birthdays were invented by Hallmark to sell cards.',
            'When I eat, it is the food that is scared.',
            'Give 100%. 110%\ is impossible. Only idiots recommend that.',
            'Capitalism: God\'s way of determining who is smart and who is poor.',
            'Fishing is for sport only. Fish meat is practically a vegetable.',
            'Friends: one to three is sufficient.',
            'There is only one bad word: taxes.',
            'Never half-ass two things. Whole-ass one thing.',
            'Any dog under fifty pounds is a cat and cats are useless.',
            'Keep your tears in your eyes where they belong.',
            'Crying: acceptable at funerals and the Grand Canyon.',
            'I would rather bleed out than sit here and talk about my feelings for 10 minutes.',
            'There are only three ways to motivate people: money, fear, and hunger.',
            'I\'d wish you the best of luck, but I believe luck is a concept created by the weak to explain their failures.',
            'Don\'t start chasing applause and acclaim. That way lies madness.',
            'Strippers do nothing for me... but I will take a free breakfast buffet anytime, anyplace.',
            'Clear alcohols are for rich women on diets.',
            'If there were more food and fewer people, this would be a perfect party.',
            'You\'ve accidentally given me the food that my food eats.',
            'An ideal night out, to me, is stepping onto my porch area and grilling up a thick slab of something\'s flesh and then popping in a highlight reel from the WNBA.',
            'Barbecues should be about one thing: good shared meat.',
            'If it doesn\'t have meat, it\'s a snack.',
            'In my opinion, not enough people have looked their dinner in the eyes and considered the circle of life.',
            'Veganism is the sad result of a morally corrupt mind. Reconsider your life.',
            'The whole point of this country is if you want to eat garbage, balloon up to 600 pounds, and die of a heart attack at 43, you can! You are free to do so. To me, that\'s beautiful.',
            'Are you going to tell a man that he can\'t fart in his own car?',
            'I like saying \'No,\' it lowers their enthusiasm.',
            'I prefer quality over flash—that\'s why I refuse to write my signature in cursive.',
            'Live your life how you want, but don\'t confuse drama with happiness.',
            'Put some alcohol in your mouth to block words from coming out.',
            'Busy? Impossible. I work for the government.',
            'Child labor laws are ruining this country.',
            'Capitalism is the only way. It makes America great, England okay, and France terrible.',
            'The less I know about other people\'s affairs, the happier I am.',
            'Creativity is for people with glasses who like to lie.',
            'I\'ve cried twice in my life. Once when I was 7 and hit by a school bus. And then again when I heard that Li\'l Sebastian had passed.',
            'Do you have any history of mental illness in your family? I have an uncle who does yoga.',
            'I like Tom. He doesn\'t do a lot of work around here. He shows zero initiative. He\'s not a team player. He\'s never wanted to go that extra mile. Tom is exactly what I\'m looking for in a government employee.',
            'I work hard to make sure my department is as small and as ineffective as possible.',
            'Well, I am not usually one for speeches. So, goodbye.',
            'We will get along just fine, though hopefully not too fine, because I am not looking for any new friends. End speech.',
            'On nights like this when the cold winds blow, the air is awash in the swirling eddies of our dreams, come with me and find safe haven in a warm bathtub full of my jazz.',
            'My son is several weeks old. He is very familiar with the sound of power tools.',
            'Say what you want about organized religion, but those bastards knew how to construct an edifice.',
            'Literally everything is a weapon, son. That folder, in my hands, is far deadlier than this bow of yours.',
            'ERASE ALL PICTURES OF RON!'

        ]
